#
# A Sample Teleport configuration file.
# Creates a single proxy, auth and node server.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#
version: v2
teleport:
  nodename: proxy
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: dk.teleportdemo.com
  proxy_listener_mode: multiplex
  license_file: /var/lib/teleport/license.pem
  authentication:
    type: local
    second_factor: webauthn
    webauthn:
      rp_id: dk.teleportdemo.com
ssh_service:
  enabled: "yes"
  labels:
    role: proxy
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: dk.teleportdemo.com:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: dan.kirkwood@goteleport.com