on:
  push:
    paths:
      - 'aws-ubuntu.pkr.hcl'

jobs:
  call-image-build-job:
    uses: ./.github/workflows/imagebuild.yaml@main
    with:
      target_file: aws-ubuntu.pkr.hcl
    secrets: inherit